export const PERMISSIONS = {
  ONBOARDING_VIEW: 'onboarding:view',
  ONBOARDING_APPROVE: 'onboarding:approve',
  LAND_VIEW: 'land:view',
  LAND_CREATE: 'land:create',
  LAND_EDIT: 'land:edit',
  LAND_VERIFY: 'land:verify',
  INSURANCE_VIEW: 'insurance:view',
  INSURANCE_APPLY: 'insurance:apply',
  CLAIM_RAISE: 'claim:raise',
  CLAIM_INSPECT: 'claim:inspect',
  SOIL_REQUEST: 'soil:request',
  SOIL_REPORT_SUBMIT: 'soil:report_submit',
  MARKETPLACE_BROWSE: 'marketplace:browse',
  MARKETPLACE_ORDER: 'marketplace:order',
  PROJECT_VIEW: 'project:view',
  PROJECT_REQUEST: 'project:request',
  TASK_EXECUTE: 'task:execute',
  WALLET_VIEW: 'wallet:view',
  WALLET_WITHDRAW_REQUEST: 'wallet:withdraw_request',
  ADMIN_AUDIT_VIEW: 'admin:audit_view',
};
