export const ROLES = {
  FARMER: 'FARMER',
  GOVERNMENT: 'GOVERNMENT',
  PARTNER: 'PARTNER',
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_STAFF: 'ADMIN_STAFF',
};

export const ROLE_LABELS = {
  FARMER: 'Farmer / Land Owner',
  GOVERNMENT: 'Government Body',
  PARTNER: 'Enterprise Partner',
  SUPER_ADMIN: 'Super Admin',
  ADMIN_STAFF: 'Admin Staff',
};

export const USER_STATUSES = {
  PENDING_ONBOARDING: 'PENDING_ONBOARDING',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  QUERY_RAISED: 'QUERY_RAISED',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
};
