export const MOCK_APPROVALS = [
  {
    id: 'appr_01',
    type: 'LAND_REGISTRATION',
    title: 'South Riverbed Expansion (Survey: 619/C)',
    applicantName: 'Jitendra Vaghela',
    applicantRole: 'FARMER',
    submittedAt: '01 Sep 2026',
    details: 'Area: 3.2 Acres • Jitodia, Anand • Documents: 7/12 RoR attached',
    status: 'PENDING_VERIFICATION',
    targetId: 'land_01',
  },
  {
    id: 'appr_02',
    type: 'FARMER_KYC',
    title: 'Aadhaar Identity & Bank KYC Verification',
    applicantName: 'Manharbhai Solanki',
    applicantRole: 'FARMER',
    submittedAt: '03 Sep 2026',
    details: 'Village Gana • Mobile: 94280 88219 • Bank: Bank of Baroda',
    status: 'PENDING_VERIFICATION',
  },
  {
    id: 'appr_03',
    type: 'INSURANCE_CLAIM',
    title: 'Damage Claim CLM-2026-0811 (18 Trees)',
    applicantName: 'Ramesh Patel',
    applicantRole: 'FARMER',
    submittedAt: '05 Sep 2026',
    details: 'Hailstorm Peril • Assessed Loss: ₹1,18,000 • Field Dossier signed by Devang Joshi',
    status: 'INSPECTION_COMPLETED',
  },
  {
    id: 'appr_04',
    type: 'PARTNER_ONBOARDING',
    title: 'Kheda AgroBio Testing Laboratories',
    applicantName: 'Dr. Suresh Mehta',
    applicantRole: 'PARTNER',
    submittedAt: '06 Sep 2026',
    details: 'NABL Certificate No: TC-8891 • Category: Soil & Foliar Testing Laboratory',
    status: 'PENDING_VERIFICATION',
  },
];
