export const MOCK_DOCUMENTS = [
  {
    id: 'doc_01',
    name: 'Aadhaar KYC Identity Document.pdf',
    category: 'IDENTITY',
    entityType: 'User',
    uploadedAt: '2026-03-01T10:00:00Z',
    fileSize: '1.4 MB',
    status: 'VERIFIED',
    verifiedBy: 'Verification Officer 04',
  },
  {
    id: 'doc_02',
    name: 'Survey 402/A Revenue Record 7-12 Extract.pdf',
    category: 'LAND',
    entityType: 'Land',
    uploadedAt: '2026-03-15T10:35:00Z',
    fileSize: '3.2 MB',
    status: 'VERIFIED',
    verifiedBy: 'Land Desk Admin',
  },
  {
    id: 'doc_03',
    name: 'Tree Policy BC-POL-2026-00481 Certificate.pdf',
    category: 'INSURANCE',
    entityType: 'InsurancePolicy',
    uploadedAt: '2026-06-01T00:05:00Z',
    fileSize: '2.1 MB',
    status: 'VERIFIED',
    verifiedBy: 'Underwriter Team',
  },
  {
    id: 'doc_04',
    name: 'Certified Soil Health Analysis Sheet SR-9921.pdf',
    category: 'SOIL',
    entityType: 'SoilRequest',
    uploadedAt: '2026-06-22T15:02:00Z',
    fileSize: '1.8 MB',
    status: 'VERIFIED',
    verifiedBy: 'National AgriBio Testing Central',
  },
];
