export const MOCK_CATEGORIES = [
  { id: 'cat_seeds', name: 'Certified High-Yield Seeds', count: 24, icon: 'Sprout' },
  { id: 'cat_organic', name: 'Bio-Fertilizers & Nutrients', count: 18, icon: 'Leaf' },
  { id: 'cat_irrigation', name: 'Smart Drip & Solar Pumps', count: 12, icon: 'Droplets' },
  { id: 'cat_saplings', name: 'Timber & Agroforestry Saplings', count: 35, icon: 'Trees' },
  { id: 'cat_equipment', name: 'Eco-Sprayers & Pruning Tools', count: 15, icon: 'Wrench' },
];

export const MOCK_PRODUCTS = [
  {
    id: 'prod_01',
    name: 'Tissue-Cultured Red Sandalwood Saplings (Pack of 25)',
    category: 'cat_saplings',
    seller: 'Gujarat State Agro Forestry Nursery',
    price: 3750,
    originalPrice: 4500,
    rating: 4.8,
    reviewsCount: 142,
    stockStatus: 'IN_STOCK',
    specs: {
      height: '1.5 - 2.0 Feet',
      age: '9 Months Hardened',
      survivalRate: '95%+ with drip care',
      certification: 'ICFRE Sovereign Certified',
    },
    description: 'Disease-resistant, high-resin heartwood clonal saplings ideal for bund planting or dedicated plantation plots.',
    deliveryEstimate: '3-5 Business Days',
  },
  {
    id: 'prod_02',
    name: 'Bio-Dynamic Liquid Organic Compost (5 Liters)',
    category: 'cat_organic',
    seller: 'Kisan Shakti Bio Nutrients',
    price: 850,
    originalPrice: 1100,
    rating: 4.9,
    reviewsCount: 88,
    stockStatus: 'IN_STOCK',
    specs: {
      composition: 'Microbial Flora + Seaweed Extract + Humic Acid 18%',
      dosage: '5ml per liter of water',
      suitability: 'All field crops, orchards and vegetables',
    },
    description: 'Enriches beneficial soil microbes, enhances organic carbon uptake, and increases root tensile strength.',
    deliveryEstimate: '2-4 Business Days',
  },
  {
    id: 'prod_03',
    name: 'Automated Solar Drip Controller with Soil Moisture Sensor',
    category: 'cat_irrigation',
    seller: 'EcoSolar Precision Tech',
    price: 6499,
    originalPrice: 7999,
    rating: 4.7,
    reviewsCount: 63,
    stockStatus: 'IN_STOCK',
    specs: {
      power: '5W Monocrystalline Solar Panel + 4000mAh Battery',
      valves: 'Dual 1-inch Solenoid support',
      connectivity: 'Bluetooth & SMS status triggers',
    },
    description: 'Save up to 45% water by triggering precision root-zone drip pulses only when soil moisture dips below optimal threshold.',
    deliveryEstimate: '4-6 Business Days',
  },
];
