export const MOCK_PROJECTS = [
  {
    id: 'prj_01',
    title: 'Mogri Gram Cluster Agroforestry & Carbon Sequestration',
    scope: 'Community bund planting of 1,200 native timber & fruit saplings with GIS tracking.',
    category: 'Civic Agroforestry',
    location: 'Mogri Panchayat, Anand, Gujarat',
    assignedPartner: 'AgriTech Field Services',
    progress: 75,
    status: 'IN_PROGRESS',
    startDate: '2026-02-01',
    targetCompletion: '2026-11-30',
    linkedLandCount: 14,
    milestones: [
      { title: 'Site GIS Mapping & Soil Baseline', completed: true, date: '15 Feb 2026' },
      { title: 'Sapling Procurement & Pit Preparation', completed: true, date: '10 Apr 2026' },
      { title: 'Drip Network Installation & Planting', completed: true, date: '25 Jun 2026' },
      { title: 'First-Quarter Survival Audit & Geotagging', completed: false, date: '15 Oct 2026' },
      { title: 'Carbon Baseline Issuance', completed: false, date: '30 Nov 2026' },
    ],
  },
  {
    id: 'prj_02',
    title: 'Charotar Regenerative Soil & Drip Optimization Mission',
    scope: 'Installation of IoT soil probes and organic compost drives across 40 farmer holdings.',
    category: 'Soil Restoration',
    location: 'Anand-Kheda Belt',
    assignedPartner: 'AgriTech Field Services',
    progress: 40,
    status: 'IN_PROGRESS',
    startDate: '2026-05-15',
    targetCompletion: '2027-01-15',
    linkedLandCount: 38,
    milestones: [
      { title: 'Farmer Mobilization & Consent Workshops', completed: true, date: '30 May 2026' },
      { title: 'Baseline Lab Soil Sampling', completed: true, date: '15 Jul 2026' },
      { title: 'Bio-Compost Distribution & Application', completed: false, date: '30 Sep 2026' },
      { title: 'Impact Assessment & Soil Carbon Audit', completed: false, date: '15 Jan 2027' },
    ],
  },
];
