export const MOCK_SCHEMES = [
  {
    id: 'sch_01',
    title: 'PM Kisan Samman Nidhi (PM-KISAN)',
    authority: 'Ministry of Agriculture & Farmers Welfare, Govt of India',
    description: 'Direct income support of ₹6,000 per year in three equal four-monthly installments to all landholding farmer families.',
    benefits: '₹6,000 / year direct bank transfer to Aadhaar-linked account.',
    eligibility: 'All landholding farmer families with cultivable landholding in their names.',
    requiredDocuments: ['Aadhaar Card', 'Land Ownership Records (7/12 & 8-A)', 'Bank Passbook'],
    deadline: 'Rolling Continuous Enrollment',
    geography: 'National (All States & UTs)',
    category: 'Income Support',
  },
  {
    id: 'sch_02',
    title: 'Paramparagat Krishi Vikas Yojana (Organic Farming Assistance)',
    authority: 'Department of Agriculture & Farmers Welfare',
    description: 'Promotes cluster-based organic farming with PGS (Participatory Guarantee System) certification and financial assistance for organic inputs.',
    benefits: 'Financial assistance of ₹50,000/ha for 3 years for inputs, certification, and packaging.',
    eligibility: 'Farmers forming clusters of 20 or more members having at least 20 hectares total land.',
    requiredDocuments: ['Group Formation Document', 'Khasra/Survey Numbers', 'Soil Test Baseline'],
    deadline: '31 December 2026',
    geography: 'National',
    category: 'Sustainable Agriculture',
  },
  {
    id: 'sch_03',
    title: 'Gujarat State Agroforestry Sapling & Drip Subsidy',
    authority: 'Gujarat State Forest & Agriculture Department',
    description: 'Provides free high-value timber saplings (Teak, Malabar Neem, Mahogany) and 70% subsidy on solar drip irrigation systems.',
    benefits: 'Free saplings + 70% capital subsidy on micro-drip networks.',
    eligibility: 'Farmers having minimum 1.0 Acre registered agricultural or wasteland parcel.',
    requiredDocuments: ['Digital 7/12 Land Extract', 'Electricity / Borewell NOC', 'Aadhaar Card'],
    deadline: '31 October 2026',
    geography: 'Gujarat',
    category: 'Agroforestry Subsidies',
  },
];
