export const MOCK_SOIL_REQUESTS = [
  {
    id: 'soil_req_01',
    requestNumber: 'SR-2026-9921',
    landId: 'lnd_01',
    landName: 'Shree Ram Farm (North Plot)',
    packageType: 'Advanced 12-Parameter Micronutrient Grid',
    fee: 850,
    status: 'REPORT_READY',
    requestedAt: '2026-06-10T09:00:00Z',
    sampleCollectedAt: '2026-06-14T11:30:00Z',
    reportReadyAt: '2026-06-22T15:00:00Z',
    assignedLab: 'National AgriBio Testing Central, Anand',
    reportData: {
      pH: { value: 7.2, rating: 'Optimal (Neutral)', range: '6.5 - 7.5' },
      organicCarbon: { value: '0.82%', rating: 'High Fertility', range: '> 0.75%' },
      nitrogen: { value: '280 kg/ha', rating: 'Medium', range: '280 - 560 kg/ha' },
      phosphorus: { value: '24 kg/ha', rating: 'High', range: '10 - 25 kg/ha' },
      potassium: { value: '310 kg/ha', rating: 'High', range: '110 - 280 kg/ha' },
      zinc: { value: '1.1 ppm', rating: 'Adequate', range: '> 0.6 ppm' },
      iron: { value: '5.4 ppm', rating: 'Adequate', range: '> 4.5 ppm' },
      recommendation: 'Soil is in prime health for cotton & pulse rotation. Supplement with 20kg/acre organic bio-potash during flowering.',
    },
  },
  {
    id: 'soil_req_02',
    requestNumber: 'SR-2026-1044',
    landId: 'lnd_02',
    landName: 'Green Valley Teak Plantation',
    packageType: 'Standard 5-Parameter Macro Health',
    fee: 450,
    status: 'TESTING',
    requestedAt: '2026-08-20T10:00:00Z',
    sampleCollectedAt: '2026-08-25T14:00:00Z',
    assignedLab: 'State Soil Testing Laboratory, Kheda',
  },
];
