export const MOCK_USERS = {
  FARMER: {
    id: 'usr_farmer_01',
    name: 'Ramesh Patel',
    mobile: '9123456780',
    email: 'ramesh.patel@bhumicred.in',
    role: 'FARMER',
    subRole: 'Individual Landholder',
    status: 'APPROVED',
    avatarUrl: '',
    jurisdiction: {
      state: 'Gujarat',
      district: 'Anand',
      taluk: 'Anand',
      village: 'Mogri',
      pincode: '388345',
    },
    kycStatus: 'VERIFIED',
    referralCode: 'RAMESH26',
  },
  GOVERNMENT: {
    id: 'usr_govt_01',
    name: 'Panchayat Officer Sharma',
    mobile: '9822334455',
    email: 'anand.panchayat@bhumicred.gov.in',
    role: 'GOVERNMENT',
    subRole: 'Gram Panchayat Officer',
    status: 'APPROVED',
    institutionType: 'Gram Panchayat',
    institutionName: 'Mogri Gram Panchayat Office',
    jurisdiction: {
      state: 'Gujarat',
      district: 'Anand',
      taluk: 'Anand',
      boundaryName: 'Mogri-Gana Cluster',
      wardsOrVillages: ['Mogri', 'Gana', 'Jitodia'],
      pincode: '388345',
    },
    kycStatus: 'VERIFIED',
    referralCode: 'GPANAND',
  },
  PARTNER: {
    id: 'usr_partner_01',
    name: 'AgriTech Field Services',
    mobile: '9988776655',
    email: 'operations@agritechservices.com',
    role: 'PARTNER',
    subRole: 'Field Inspection & Soil Testing Agency',
    status: 'APPROVED',
    organizationName: 'AgriTech Certified Field Partners Pvt Ltd',
    authorizedPerson: 'Dr. Alok Verma',
    serviceCapabilities: ['SOIL_TESTING', 'TREE_INSPECTION', 'LAND_SURVEY', 'PROJECT_EXECUTION'],
    operatingGeography: [
      { state: 'Gujarat', districts: ['Anand', 'Kheda', 'Vadodara'] },
      { state: 'Maharashtra', districts: ['Pune', 'Nashik'] },
    ],
    kycStatus: 'VERIFIED',
    referralCode: 'AGRIPARTNER',
  },
  SUPER_ADMIN: {
    id: 'usr_admin_01',
    name: 'Super Administrator',
    mobile: '9876543210',
    email: 'admin@bhumicred.gov.in',
    role: 'SUPER_ADMIN',
    subRole: 'Platform Governance Lead',
    status: 'APPROVED',
    kycStatus: 'VERIFIED',
    referralCode: 'ADMIN2026',
  },
};
